### ISSUE TITLE
bug in RL reporting

### ISSUE THREAD

**Issue by optimass** [lebrice/Sequoia#110]
```console 
$ /mnt/home/.conda/envs/sequoia/bin/sequoia_sweep  --setting incremental_rl --max_runs 2 --dataset monsterkong --nb_tasks 10 --method baseline --project monsterkong_sweep --steps_per_task 1000000
2021-02-23:16:03:01,949 INFO     [sequoia/methods/models/baseline_model/base_model.py:136] Moving encoder to device cuda
2021-02-23:16:03:05,15 WARNING  [sequoia/methods/models/output_heads/output_head.py:137] Upgrading the hparams from type <class 'sequoia.methods.models.output_heads.output_head.OutputHead.HParams'> to type <class 'sequoia.methods.models.output_heads.rl.episodic_a2c.EpisodicA2C.HParams'>. This will try to fetch the values for the missing fields ['hidden_layers', 'hidden_neurons', 'activation', 'dropout_prob', 'gamma', 'max_episode_window_length', 'min_episodes_before_update', 'max_steps_between_updates', 'accumulate_losses_before_backward', 'normalize_advantages', 'actor_loss_coef', 'critic_loss_coef', 'entropy_loss_coef', 'max_policy_grad_norm'] from the command-line. 
2021-02-23:16:03:05,49 WARNING  [sequoia/utils/parseable.py:212] Upgrading the hparams from type <class 'sequoia.methods.models.output_heads.output_head.OutputHead.HParams'> to type <class 'sequoia.methods.models.output_heads.rl.episodic_a2c.EpisodicA2C.HParams'>. This will try to fetch the values for the missing fields ['hidden_layers', 'hidden_neurons', 'activation', 'dropout_prob', 'gamma', 'max_episode_window_length', 'min_episodes_before_update', 'max_steps_between_updates', 'accumulate_losses_before_backward', 'normalize_advantages', 'actor_loss_coef', 'critic_loss_coef', 'entropy_loss_coef', 'max_policy_grad_norm'] from the command-line. 
2021-02-23:16:03:05,75 INFO     [sequoia/common/config/wandb_config.py:104] Creating a WandbLogger with using options WandbLoggerConfig(entity='', project='monsterkong_sweep', group=None, run_name='baseline-incremental_rl-MetaMonsterKong-v0', run_id=None, tags=[], notes=None, offline=False, anonymous=False, version=None, log_model=False, monitor_gym=True).
2021-02-23:16:03:05,80 INFO     [pytorch_lightning.utilities.distributed:54] GPU available: True, used: True
2021-02-23:16:03:05,80 INFO     [pytorch_lightning.utilities.distributed:54] TPU available: None, using: 0 TPU cores
2021-02-23:16:03:05,80 INFO     [pytorch_lightning.accelerators.accelerator_connector:396] LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
2021-02-23:16:03:06,319 INFO     [sequoia/settings/base/bases.py:582] HPO Search space:
{
        "hparams": {
                "learning_rate": "loguniform(1e-06, 1e-02, default_value=0.001)",
                "weight_decay": "loguniform(1e-12, 1e-03, default_value=1e-06)",
                "optimizer": "choices(['sgd', 'adam', 'rmsprop'], default_value='adam')",
                "output_head": {
                        "activation": "choices(['relu', 'tanh', 'elu', 'gelu', 'relu6'], default_value='tanh')",
                        "dropout_prob": "uniform(0, 0.8, default_value=0.2)",
                        "gamma": "uniform(0.9, 0.999, default_value=0.99)",
                        "normalize_advantages": "choices([True, False], default_value=False)",
                        "actor_loss_coef": "uniform(0.1, 1, default_value=0.5)",
                        "critic_loss_coef": "uniform(0.1, 1, default_value=0.5)",
                        "entropy_loss_coef": "uniform(0, 1, discrete=True, default_value=0)"
                }
        },
        "trainer_options": {
                "max_epochs": "uniform(1, 100, discrete=True, default_value=10)"
        }
}
2021-02-23:16:03:06,319 INFO     [sequoia/settings/base/bases.py:585] Will use database at path 'orion_db.pkl'.
2021-02-23:16:03:06,975 INFO     [orion.core.io.experiment_builder:458] Many versions for experiment baseline-incremental_rl_MetaMonsterKong-v0_51845 have been found. Using latest version 2.
Traceback (most recent call last):
  File "/mnt/home/.conda/envs/sequoia/bin/sequoia_sweep", line 33, in <module>
    sys.exit(load_entry_point('sequoia', 'console_scripts', 'sequoia_sweep')())
  File "/mnt/home/dev/Sequoia/sequoia/experiments/hpo_sweep.py", line 122, in main
    return HPOSweep.main()
  File "/mnt/home/dev/Sequoia/sequoia/experiments/hpo_sweep.py", line 118, in main
    return experiment.launch(argv, strict_args=strict_args)
  File "/mnt/home/dev/Sequoia/sequoia/experiments/hpo_sweep.py", line 68, in launch
    best_params, best_objective = self.method.hparam_sweep(
  File "/mnt/home/dev/Sequoia/sequoia/methods/baseline_method.py", line 451, in hparam_sweep
    return super().hparam_sweep(
  File "/mnt/home/dev/Sequoia/sequoia/settings/base/bases.py", line 604, in hparam_sweep
    lower_is_better = setting.Results.lower_is_better
AttributeError: type object 'RLResults' has no attribute 'lower_is_better'
```

**Comment by lebrice** [comment]
Yeah that's a neat little bug you got there!
(Worth noting, that bug is only happening on the PR branch `lebrice/issue46`, correct?

To fix this, just add a class attribute on the RLResults object, like so:
```python
class RLResults(IncrementalSetting.Results):
    lower_is_better: ClassVar[bool] = False # Since a higher CL score == better
```

Also, while you're at it, would you mind also adding the same attribute on the classes [`TaskResults`](sequoia/settings/assumptions/iid_results.py), [`TaskSequenceResults`](sequoia/settings/assumptions/incremental_results.py) and [`IncrementalResults`]((sequoia/settings/assumptions/incremental_results.py)) ? (since in all of these cases, the `objective` attribute being higher means that the results is better?

If not, I can also make a quickfix for that later today
