### ISSUE TITLE
Gradient computation issue

### ISSUE THREAD

**Issue by oleksost** [lebrice/Sequoia#113]
`Getting this error when running sweeps:`
```

[W python_anomaly_mode.cpp:104] Warning: Error detected in CudnnBatchNormBackward. Traceback of forward call that caused the error:
  File "/home/mila/o/ostapeno/ENV/SSCL/bin/sequoia_sweep", line 33, in <module>
    sys.exit(load_entry_point('sequoia', 'console_scripts', 'sequoia_sweep')())
  File "/home/mila/o/ostapeno/dev/Sequoia/sequoia/experiments/hpo_sweep.py", line 122, in main
    return HPOSweep.main()
  File "/home/mila/o/ostapeno/dev/Sequoia/sequoia/experiments/hpo_sweep.py", line 118, in main
    return experiment.launch(argv, strict_args=strict_args)
  File "/home/mila/o/ostapeno/dev/Sequoia/sequoia/experiments/hpo_sweep.py", line 73, in launch
    max_runs=self.max_runs,
  File "/home/mila/o/ostapeno/dev/Sequoia/sequoia/methods/baseline_method.py", line 457, in hparam_sweep
    debug = debug or self.config.debug,
  File "/home/mila/o/ostapeno/dev/Sequoia/sequoia/settings/base/bases.py", line 633, in hparam_sweep
    result: Results = setting.apply(self)
  File "/home/mila/o/ostapeno/dev/Sequoia/sequoia/settings/active/continual/continual_rl_setting.py", line 535, in apply
    results = self.main_loop(method)
  File "/home/mila/o/ostapeno/dev/Sequoia/sequoia/settings/assumptions/incremental.py", line 188, in main_loop
    train_env=task_train_loader, valid_env=task_valid_loader,
  File "/home/mila/o/ostapeno/dev/Sequoia/sequoia/methods/baseline_method.py", line 293, in fit
    model=self.model, train_dataloader=train_env, val_dataloaders=valid_env,
  File "/home/mila/o/ostapeno/ENV/SSCL/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 513, in fit
    self.dispatch()
  File "/home/mila/o/ostapeno/ENV/SSCL/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 553, in dispatch
    self.accelerator.start_training(self)
  File "/home/mila/o/ostapeno/ENV/SSCL/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 74, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/mila/o/ostapeno/ENV/SSCL/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 111, in start_training
    self._results = trainer.run_train()
  File "/home/mila/o/ostapeno/ENV/SSCL/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 644, in run_train
    self.train_loop.run_training_epoch()
  File "/home/mila/o/ostapeno/ENV/SSCL/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 492, in run_training_epoch
    batch_output = self.run_training_batch(batch, batch_idx, dataloader_idx)
  File "/home/mila/o/ostapeno/ENV/SSCL/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 654, in run_training_batch
    split_batch, batch_idx, opt_idx, self.trainer.hiddens
  File "/home/mila/o/ostapeno/ENV/SSCL/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 293, in training_step
    training_step_output = self.trainer.accelerator.training_step(args)
  File "/home/mila/o/ostapeno/ENV/SSCL/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 157, in training_step
    return self.training_type_plugin.training_step(*args)
  File "/home/mila/o/ostapeno/ENV/SSCL/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/dp.py", line 61, in training_step
    return self.model(*args, **kwargs)
  File "/home/mila/o/ostapeno/ENV/SSCL/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/mila/o/ostapeno/ENV/SSCL/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 159, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/mila/o/ostapeno/ENV/SSCL/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/mila/o/ostapeno/ENV/SSCL/lib/python3.7/site-packages/pytorch_lightning/overrides/data_parallel.py", line 74, in forward
    output = super().forward(*inputs, **kwargs)
  File "/home/mila/o/ostapeno/ENV/SSCL/lib/python3.7/site-packages/pytorch_lightning/overrides/base.py", line 48, in forward
    output = self.module.training_step(*inputs, **kwargs)
  File "/home/mila/o/ostapeno/dev/Sequoia/sequoia/methods/models/baseline_model/baseline_model.py", line 261, in training_step
    **kwargs
  File "/home/mila/o/ostapeno/dev/Sequoia/sequoia/methods/models/baseline_model/baseline_model.py", line 324, in shared_step
    results = super().shared_step(batch, batch_idx, environment, loss_name, dataloader_idx=dataloader_idx, optimizer_idx=optimizer_idx)
  File "/home/mila/o/ostapeno/dev/Sequoia/sequoia/methods/models/baseline_model/multihead_model.py", line 411, in shared_step
    optimizer_idx=optimizer_idx,
  File "/home/mila/o/ostapeno/dev/Sequoia/sequoia/methods/models/baseline_model/base_model.py", line 355, in shared_step
    forward_pass: ForwardPass = self(observations)
  File "/home/mila/o/ostapeno/ENV/SSCL/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/mila/o/ostapeno/ENV/SSCL/lib/python3.7/site-packages/pytorch_lightning/core/decorators.py", line 62, in auto_transfer_args
    return fn(self, *args, **kwargs)
  File "/home/mila/o/ostapeno/dev/Sequoia/sequoia/methods/models/baseline_model/baseline_model.py", line 209, in forward
    forward_pass = super().forward(observations)
  File "/home/mila/o/ostapeno/ENV/SSCL/lib/python3.7/site-packages/pytorch_lightning/core/decorators.py", line 62, in auto_transfer_args
    return fn(self, *args, **kwargs)
  File "/home/mila/o/ostapeno/dev/Sequoia/sequoia/methods/models/baseline_model/multihead_model.py", line 180, in forward
    forward_pass = super().forward(observations)
  File "/home/mila/o/ostapeno/ENV/SSCL/lib/python3.7/site-packages/pytorch_lightning/core/decorators.py", line 62, in auto_transfer_args
    return fn(self, *args, **kwargs)
  File "/home/mila/o/ostapeno/dev/Sequoia/sequoia/methods/models/baseline_model/base_model.py", line 155, in forward
    representations = self.encode(observations)
  File "/home/mila/o/ostapeno/dev/Sequoia/sequoia/methods/models/baseline_model/base_model.py", line 199, in encode
    h_x = self.encoder(x)
  File "/home/mila/o/ostapeno/ENV/SSCL/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/mila/o/ostapeno/dev/Sequoia/sequoia/methods/models/simple_convnet.py", line 92, in forward
    return self.fc(self.features(x))
  File "/home/mila/o/ostapeno/ENV/SSCL/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/mila/o/ostapeno/ENV/SSCL/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/mila/o/ostapeno/ENV/SSCL/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/mila/o/ostapeno/ENV/SSCL/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 136, in forward
    self.weight, self.bias, bn_training, exponential_average_factor, self.eps)
  File "/home/mila/o/ostapeno/ENV/SSCL/lib/python3.7/site-packages/torch/nn/functional.py", line 2058, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
 (function _print_stack)
Epoch 0:   1%|          | 1001/101000 [59:04<98:21:32,  3.54s/it, v_num=pne1, train Loss=0.203, train episodic_a2c Loss=0.203, train episodic_a2c Mean reward per episode=0.000, train episodic_a2c gradient_usage used_fraction=1.000, train episodic_a2c actor Loss=8.33e-8, train episodic_a2c critic Loss=0.203, train episodic_a2c entropy Loss=-]
Traceback (most recent call last):
  File "/home/mila/o/ostapeno/ENV/SSCL/bin/sequoia_sweep", line 33, in <module>
    sys.exit(load_entry_point('sequoia', 'console_scripts', 'sequoia_sweep')())
  File "/home/mila/o/ostapeno/dev/Sequoia/sequoia/experiments/hpo_sweep.py", line 122, in main
    return HPOSweep.main()
  File "/home/mila/o/ostapeno/dev/Sequoia/sequoia/experiments/hpo_sweep.py", line 118, in main
    return experiment.launch(argv, strict_args=strict_args)
  File "/home/mila/o/ostapeno/dev/Sequoia/sequoia/experiments/hpo_sweep.py", line 73, in launch
    max_runs=self.max_runs,
  File "/home/mila/o/ostapeno/dev/Sequoia/sequoia/methods/baseline_method.py", line 457, in hparam_sweep
    debug = debug or self.config.debug,
  File "/home/mila/o/ostapeno/dev/Sequoia/sequoia/settings/base/bases.py", line 633, in hparam_sweep
    result: Results = setting.apply(self)
  File "/home/mila/o/ostapeno/dev/Sequoia/sequoia/settings/active/continual/continual_rl_setting.py", line 535, in apply
    results = self.main_loop(method)
  File "/home/mila/o/ostapeno/dev/Sequoia/sequoia/settings/assumptions/incremental.py", line 188, in main_loop
    train_env=task_train_loader, valid_env=task_valid_loader,
  File "/home/mila/o/ostapeno/dev/Sequoia/sequoia/methods/baseline_method.py", line 293, in fit
    model=self.model, train_dataloader=train_env, val_dataloaders=valid_env,
  File "/home/mila/o/ostapeno/ENV/SSCL/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 513, in fit
    self.dispatch()
  File "/home/mila/o/ostapeno/ENV/SSCL/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 553, in dispatch
    self.accelerator.start_training(self)
  File "/home/mila/o/ostapeno/ENV/SSCL/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 74, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/mila/o/ostapeno/ENV/SSCL/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 111, in start_training
    self._results = trainer.run_train()
  File "/home/mila/o/ostapeno/ENV/SSCL/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 644, in run_train
    self.train_loop.run_training_epoch()
  File "/home/mila/o/ostapeno/ENV/SSCL/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 492, in run_training_epoch
    batch_output = self.run_training_batch(batch, batch_idx, dataloader_idx)
  File "/home/mila/o/ostapeno/ENV/SSCL/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 654, in run_training_batch
    split_batch, batch_idx, opt_idx, self.trainer.hiddens
  File "/home/mila/o/ostapeno/ENV/SSCL/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 293, in training_step
    training_step_output = self.trainer.accelerator.training_step(args)
  File "/home/mila/o/ostapeno/ENV/SSCL/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 157, in training_step
    return self.training_type_plugin.training_step(*args)
  File "/home/mila/o/ostapeno/ENV/SSCL/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/dp.py", line 61, in training_step
    return self.model(*args, **kwargs)
  File "/home/mila/o/ostapeno/ENV/SSCL/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/mila/o/ostapeno/ENV/SSCL/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 159, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/mila/o/ostapeno/ENV/SSCL/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/mila/o/ostapeno/ENV/SSCL/lib/python3.7/site-packages/pytorch_lightning/overrides/data_parallel.py", line 74, in forward
    output = super().forward(*inputs, **kwargs)
  File "/home/mila/o/ostapeno/ENV/SSCL/lib/python3.7/site-packages/pytorch_lightning/overrides/base.py", line 48, in forward
    output = self.module.training_step(*inputs, **kwargs)
  File "/home/mila/o/ostapeno/dev/Sequoia/sequoia/methods/models/baseline_model/baseline_model.py", line 279, in training_step
    self.manual_backward(loss, optimizer, retain_graph=not update_model)
  File "/home/mila/o/ostapeno/ENV/SSCL/lib/python3.7/site-packages/pytorch_lightning/core/lightning.py", line 1222, in manual_backward
    self.trainer.train_loop.backward(loss, optimizer=None, opt_idx=None, *args, **kwargs)
  File "/home/mila/o/ostapeno/ENV/SSCL/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 772, in backward
    self.trainer.accelerator.backward(result, optimizer, opt_idx, should_accumulate, *args, **kwargs)
  File "/home/mila/o/ostapeno/ENV/SSCL/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 258, in backward
    self.lightning_module, closure_loss, optimizer, optimizer_idx, should_accumulate, *args, **kwargs
  File "/home/mila/o/ostapeno/ENV/SSCL/lib/python3.7/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 73, in backward
    closure_loss.backward(*args, **kwargs)
  File "/home/mila/o/ostapeno/ENV/SSCL/lib/python3.7/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/mila/o/ostapeno/ENV/SSCL/lib/python3.7/site-packages/torch/autograd/__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [32]] is at version 2; expected version 1 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!
```

**Comment by lebrice** [comment]
What branch/commit were you on btw?

**Comment by oleksost** [comment]
`d473808 (HEAD -> master, origin/master, origin/HEAD) Fix missing 'lower_is_better' attribute (#111)` <- commit 
Its this run: https://wandb.ai/sequoia/sweep/runs/1xi6pne1

**Comment by oleksost** [comment]
Not sure if this log output is relevant:
```
2021-02-24:07:12:59,483 INFO     [sequoia/settings/base/bases.py:627] Suggested values for this run:
{
	"hparams": {
		"learning_rate": 0.000547,
		"optimizer": "rmsprop",
		"output_head": {
			"activation": "elu",
			"actor_loss_coef": 0.379,
			"critic_loss_coef": 0.6995,
			"dropout_prob": 0.4018,
			"entropy_loss_coef": 0,
			"gamma": 0.9623,
			"normalize_advantages": true
		},
		"weight_decay": 3.81e-06
	},
	"trainer_options": {
		"max_epochs": 17
	}
}

```

**Comment by lebrice** [comment]
Closing this, as the above command doesn't produce an error, and I did a rework of the `MultiHeadModel` class, this issue has probably been resolved.
