### ISSUE TITLE
bug with monsterkong

### ISSUE THREAD

**Issue by optimass** [lebrice/Sequoia#146]
```console 
$ sequoia_sweep --setting rl  --max_runs 100  --benchmark monsterkong_3each  --method baseline  --project monsterkong_sweep  --steps_per_task 100000   --monitor_training_performance --database_path rl_monsterkong_3each_baseline.pkl
Validation sanity check: 0it [00:00, ?it/s]
Validation sanity check:   0%|          | 0/1 [00:00<?, ?it/s]
                                                              

Training: 0it [00:00, ?it/s]
Training:   0%|          | 0/2 [00:00<?, ?it/s]
Epoch 0:   0%|          | 0/2 [00:00<?, ?it/s] 
Epoch 0:  50%|█████     | 1/2 [00:00<00:00,  6.32it/s]
Epoch 0:  50%|█████     | 1/2 [00:00<00:00,  6.31it/s, v_num=]

Validating: 0it [00:00, ?it/s][A

Validating:   0%|          | 0/1 [00:00<?, ?it/s][A
Epoch 0: 100%|██████████| 2/2 [00:00<00:00, 12.15it/s, v_num=]
Traceback (most recent call last):
  File "/mnt/home/.conda/envs/sequoia/bin/sequoia_sweep", line 33, in <module>
    sys.exit(load_entry_point('sequoia', 'console_scripts', 'sequoia_sweep')())
  File "/mnt/home/dev/Sequoia/sequoia/experiments/hpo_sweep.py", line 122, in main
    return HPOSweep.main()
  File "/mnt/home/dev/Sequoia/sequoia/experiments/hpo_sweep.py", line 118, in main
    return experiment.launch(argv, strict_args=strict_args)
  File "/mnt/home/dev/Sequoia/sequoia/experiments/hpo_sweep.py", line 68, in launch
    best_params, best_objective = self.method.hparam_sweep(
  File "/mnt/home/dev/Sequoia/sequoia/methods/baseline_method.py", line 450, in hparam_sweep
    return super().hparam_sweep(
  File "/mnt/home/dev/Sequoia/sequoia/settings/base/bases.py", line 706, in hparam_sweep
    result: Results = setting.apply(self)
  File "/mnt/home/dev/Sequoia/sequoia/settings/active/continual/continual_rl_setting.py", line 565, in apply
    results = self.main_loop(method)
  File "/mnt/home/dev/Sequoia/sequoia/settings/assumptions/incremental.py", line 221, in main_loop
    method.fit(
  File "/mnt/home/dev/Sequoia/sequoia/methods/baseline_method.py", line 283, in fit
    success = self.trainer.fit(
  File "/mnt/home/.conda/envs/sequoia/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 513, in fit
    self.dispatch()
  File "/mnt/home/.conda/envs/sequoia/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 553, in dispatch
    self.accelerator.start_training(self)
  File "/mnt/home/.conda/envs/sequoia/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 74, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/mnt/home/.conda/envs/sequoia/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 111, in start_training
    self._results = trainer.run_train()
  File "/mnt/home/.conda/envs/sequoia/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 644, in run_train
    self.train_loop.run_training_epoch()
  File "/mnt/home/.conda/envs/sequoia/lib/python3.8/site-packages/pytorch_lightning/trainer/training_loop.py", line 564, in run_training_epoch
    self.trainer.run_evaluation(on_epoch=True)
  File "/mnt/home/.conda/envs/sequoia/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 719, in run_evaluation
    for batch_idx, batch in enumerate(dataloader):
  File "/mnt/home/dev/Sequoia/sequoia/common/gym_wrappers/env_dataset.py", line 207, in __iter__
    raise gym.error.ClosedEnvironmentError(f"Env has already reached step limit ({self.max_steps}) and is closed.")
gym.error.ClosedEnvironmentError: Env has already reached step limit (1) and is closed.
```

**Comment by optimass** [comment]
here is my preset for monsterkong_5jumps_5ladders
```
dataset: monsterkong
test_steps_per_task: 10_000
train_task_schedule:
  0:
    level: 0
  1:
    level: 1
  2:
    level: 2
  3:
    level: 3
  4:
    level: 4
  5:
    level: 10
  6:
    level: 11
  7:
    level: 12
  8:
    level: 13
  9:
    level: 14
```

**Comment by optimass** [comment]
same error in `task_incremental_rl`

**Comment by optimass** [comment]
i'm not getting this bug if I don't use the benchmark preset

**Comment by optimass** [comment]
ok this bug comes from not presetting `steps_per_task`

**Comment by lebrice** [comment]
I'm surprised it even got to that point, honestly. It's supposed to raise a RuntimeError whenever you try to use a benchmark file while also trying to configure the setting from the command-line at the same time.

I don't currently see an easy way of doing both, where you could load a bunch of options from a file, and then specify other options from the command-line.. If you want to specify a custom task schedule, and that's the main reason for using a benchmark, then you could also use `--train_task_schedule_path` to point to some json file, rather than using --benchmark, but it's a bit annoying to have to do this, for sure.
I'd love to simplify this somehow, let me know what you think.
