### ISSUE TITLE
bug with DQN

### ISSUE THREAD

**Issue by optimass** [lebrice/Sequoia#149]
```console
$ sequoia_sweep --setting rl  --max_runs 100  --dataset monsterkong  --nb_task 10  --method dqn  --project monsterkong_sweep  --steps_per_task 200000  --monitor_training_performance
 
2021-03-16:00:57:19,992 INFO     [sequoia/settings/assumptions/incremental.py:232] Finished Training on task 0.

Test:   0%|          | 0/10000 [00:00<?, ?it/s]
Test:   0%|          | 8/10000 [00:00<00:45, 219.72it/s]
Traceback (most recent call last):
  File "/mnt/home/dev/Sequoia/sequoia/settings/assumptions/incremental.py", line 382, in test_loop
    method.test(test_env)
  File "/mnt/home/dev/Sequoia/sequoia/settings/base/bases.py", line 307, in test
    raise NotImplementedError
NotImplementedError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/mnt/home/.conda/envs/sequoia/bin/sequoia_sweep", line 33, in <module>
    sys.exit(load_entry_point('sequoia', 'console_scripts', 'sequoia_sweep')())
  File "/mnt/home/dev/Sequoia/sequoia/experiments/hpo_sweep.py", line 122, in main
    return HPOSweep.main()
  File "/mnt/home/dev/Sequoia/sequoia/experiments/hpo_sweep.py", line 118, in main
    return experiment.launch(argv, strict_args=strict_args)
  File "/mnt/home/dev/Sequoia/sequoia/experiments/hpo_sweep.py", line 68, in launch
    best_params, best_objective = self.method.hparam_sweep(
  File "/mnt/home/dev/Sequoia/sequoia/settings/base/bases.py", line 706, in hparam_sweep
    result: Results = setting.apply(self)
  File "/mnt/home/dev/Sequoia/sequoia/settings/active/continual/continual_rl_setting.py", line 565, in apply
    results = self.main_loop(method)
  File "/mnt/home/dev/Sequoia/sequoia/settings/assumptions/incremental.py", line 233, in main_loop
    test_metrics: TaskSequenceResults = self.test_loop(method)
  File "/mnt/home/dev/Sequoia/sequoia/settings/assumptions/incremental.py", line 426, in test_loop
    action = method.get_actions(obs, action_space)
  File "/mnt/home/dev/Sequoia/sequoia/methods/stable_baselines3_methods/dqn.py", line 175, in get_actions
    return super().get_actions(
  File "/mnt/home/dev/Sequoia/sequoia/methods/stable_baselines3_methods/base.py", line 279, in get_actions
    assert action in action_space, (observations, action, action_space)
AssertionError: (ContinualRLSetting.Observations(x=array([[[160,  97,  40],
        [202, 124,  51],
        [183, 112,  47],
        ...,
        [190, 117,  50],
        [203, 124,  52],
        [166,  98,  42]],
       [[189, 117,  47],
        [211, 130,  53],
        [191, 117,  47],
        ...,
        [216, 137,  54],
        [209, 129,  52],
        [178, 106,  44]],
       [[170, 104,  41],
        [195, 120,  49],
        [174, 107,  44],
        ...,
        [201, 125,  51],
        [191, 117,  48],
        [166,  98,  42]],
       ...,
       [[178, 112,  45],
        [217, 138,  55],
        [196, 124,  51],
        ...,
        [209, 134,  55],
        [218, 138,  55],
        [181, 110,  47]],
       [[187, 116,  46],
        [211, 130,  52],
        [189, 116,  47],
        ...,
        [214, 136,  54],
        [210, 129,  52],
        [177, 106,  44]],
       [[156,  93,  37],
        [182, 110,  46],
        [166,  99,  42],
        ...,
        [186, 112,  47],
        [178, 108,  45],
        [160,  92,  40]]], dtype=uint8), task_labels=0, done=None), array([4, 4, 4, 4, 2, 0, 3, 4, 4, 1, 3, 4, 5, 3, 1, 5, 4, 0, 1, 5, 3, 4,
       4, 2, 5, 5, 0, 4, 3, 2, 5, 5, 2, 4, 4, 5, 2, 1, 0, 3, 4, 0, 0, 2,
       0, 1, 3, 0, 5, 5, 4, 4, 3, 4, 3, 4, 4, 1, 5, 0, 2, 5, 1, 2]), Discrete(6))
wandb: Network error (ReadTimeout), entering retry loop. See wandb/debug-internal.log for full traceback.
wandb: Network error resolved after 0:00:58.176990, resuming normal operation.
wandb: Network error (HTTPError), entering retry loop. See wandb/debug-internal.log for full traceback.
wandb: Network error resolved after 0:01:26.480207, resuming normal operation.
wandb: Network error (HTTPError), entering retry loop. See wandb/debug-internal.log for full traceback.
wandb: Network error resolved after 0:00:08.483608, resuming normal operation.
wandb: Network error (HTTPError), entering retry loop. See wandb/debug-internal.l
```

**Comment by lebrice** [comment]
Here's my understanding of the problem:
The observations given to `model.predict(obs)` [here](https://github.com/lebrice/Sequoia/blob/0f53884bc43ca34ffee95de518a2de4c0f15f64f/sequoia/methods/stable_baselines3_methods/base.py#L289) have a shape of [64, 64, 3], rather than the expected [3, 64, 64], which causes the DQN to, somehow, give back a batch of 64 actions, rather than a single one.
